[line_break]
disabled = true

[git_status]
conflicted = "="
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "\\$${count}"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
