#!/usr/bin/env sh
yabai  -m signal -add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_border                off
yabai -m config window_shadow                on
yabai -m config active_window_border_color   0xff008bff
yabai -m config normal_window_border_color   0x01000000
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  16
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   16

# rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add class="^SunAwtDialog$" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="choose" manage=off mouse_follows_focus=off
#yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'
